#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

switch (strtolower($_SERVER['PWD'])) {
    case '/home/vikas/www/helpinout':
        $config = require(__DIR__ . '/config/local_console_vk.php');
        break;
    case '/home/helpinout/beta':
        $config = require(__DIR__ . '/config/beta_console.php');
        break;
    default:
        //$config = require(__DIR__ . '/config/beta_console.php');
        //$config = require(__DIR__ . '/config/local_console_govind.php');
        $config = require(__DIR__ . '/config/prod_console.php');
        break;
}


$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
